//! Paladin class — righteous strike, holy light, consecration, divine steed.
//! Resource: Holy Power (generated by attacks, spent on heals).

pub mod abilities;
pub mod auto_attack;
pub mod passives;
pub use abilities::*;
pub use auto_attack::*;
pub use passives::*;

pub fn resource_config() -> ir_core::ClassResource {
    ir_core::ClassResource::new(5.0, 0.5)
}
