//! Paladin class — righteous strike, holy light, consecration, divine steed.
//! Resource: Holy Power (generated by attacks, spent on heals).

use bevy::prelude::*;
use ir_core::*;

/// Resource config
pub fn resource_config() -> ClassResource {
    ClassResource::new(5.0, 0.5) // 5 Holy Power, regen 0.5/sec
}

// ── Primary: Righteous Strike ───────────────────────────────────────────

/// Melee cone attack that generates 1 Holy Power on hit.
pub fn primary_righteous_strike(
    commands: &mut Commands,
    attacker: Entity,
    transform: &Transform,
    stats: &CombatStats,
    _enemies: &Query<(Entity, &Transform), With<Enemy>>,
    _damage_events: &mut EventWriter<DamageEvent>,
    _dmg_num_events: &mut EventWriter<DamageNumberEvent>,
    _impact_events: &mut EventWriter<SpawnImpactEvent>,
) {
    let dmg = (12.0 + stats.damage_bonus * 1.2).max(1.0);
    commands.spawn((
        DamageHitbox::new(
            HitboxShape::Cone { range: 3.5, half_angle: 0.5 },
            dmg,
            attacker,
            DamageType::Physical,
            0.15,
            ProjectileOwner::Player,
            1.5,
        )
        .with_hit_reaction(0.1, 0.15, 0.05),
        Transform {
            translation: transform.translation,
            rotation: transform.rotation,
            ..default()
        },
    ));
}

// ── Secondary: Holy Light ─────────────────────────────────────────────────

/// Heals the paladin by 30% of max HP. Consumes 3 Holy Power.
pub fn secondary_holy_light(
    commands: &mut Commands,
    player: Entity,
) {
    commands.entity(player).insert(HolyLight { heal_pct: 0.3 });
}

/// Heal-over-time marker for the Paladin's Holy Light ability.
#[derive(Component)]
pub struct HolyLight {
    /// Percentage of max HP to heal (0.0–1.0).
    pub heal_pct: f32,
}

/// Applies HolyLight heal to player.
pub fn apply_holy_light(
    mut commands: Commands,
    mut health_query: Query<&mut Health, With<Player>>,
    holy_light_query: Query<(Entity, &HolyLight)>,
) {
    for (entity, light) in holy_light_query.iter() {
        if let Ok(mut health) = health_query.get_mut(entity) {
            let heal_amount = health.max * light.heal_pct;
            health.heal(heal_amount);
            info!("Paladin healed for {}", heal_amount);
        }
        commands.entity(entity).remove::<HolyLight>();
    }
}

// ── Cast: Consecration ────────────────────────────────────────────────────

/// A ground-targeted AoE field that damages enemies inside.
#[derive(Component)]
pub struct ConsecrationField {
    /// Remaining lifetime in seconds.
    pub lifetime: f32,
    /// Time until next damage tick.
    pub tick_timer: f32,
    /// Damage dealt per tick.
    pub damage: f32,
}

/// Spawns a consecration AoE field at the paladin's position.
pub fn cast_consecration(
    commands: &mut Commands,
    transform: &Transform,
    _stats: &CombatStats,
) {
    commands.spawn((
        ConsecrationField {
            lifetime: 6.0,
            tick_timer: 0.0,
            damage: 8.0,
        },
        Transform {
            translation: transform.translation,
            rotation: transform.rotation,
            ..default()
        },
    ));
}

/// Ticks consecration fields, damaging enemies inside.
pub fn tick_consecration(
    mut commands: Commands,
    time: Res<Time>,
    mut fields: Query<(Entity, &mut ConsecrationField, &Transform)>,
    enemies: Query<(Entity, &Transform), With<Enemy>>,
    mut damage_events: EventWriter<DamageEvent>,
) {
    for (field_entity, mut field, field_tf) in fields.iter_mut() {
        field.tick_timer -= time.delta_secs();
        if field.tick_timer > 0.0 {
            continue;
        }
        field.tick_timer = 1.0; // tick every 1 second
        field.lifetime -= time.delta_secs();

        for (enemy_entity, enemy_tf) in enemies.iter() {
            let dist = field_tf.translation.distance(enemy_tf.translation);
            if dist < 3.0 {
                damage_events.send(DamageEvent {
                    target: enemy_entity,
                    source: field_entity,
                    amount: field.damage,
                    is_critical: false,
                    damage_type: DamageType::Magic,
                    hit_position: None,
                });
            }
        }

        if field.lifetime <= 0.0 {
            commands.entity(field_entity).despawn();
        }
    }
}

// ── Holy Power Generation ────────────────────────────────────────────────

/// Generates 1 Holy Power when the paladin deals damage (from hitbox processing).
/// Called alongside the damage pipeline.
pub fn paladin_holy_power_on_hit(
    mut damage_events: EventReader<DamageEvent>,
    mut player_query: Query<&mut ClassResource, (With<Player>, With<PlayerClass>)>,
) {
    let Ok(mut resource) = player_query.get_single_mut() else { return };
    // Identify paladin by resource config: max=5, regen=0.5
    if (resource.max - 5.0).abs() > 0.1 || (resource.regen_rate - 0.5).abs() > 0.1 {
        return;
    }
    for event in damage_events.read() {
        // Only from player-sourced damage to enemies
        if event.damage_type == DamageType::Physical || event.damage_type == DamageType::Magic {
            resource.current = (resource.current + 1.0).min(resource.max);
        }
    }
}

// ── Dash: Divine Steed ────────────────────────────────────────────────────

/// Dash ability for Paladin: Divine Steed (standard dodge).
///
/// This is a placeholder — the dash behavior is handled by the
/// generic `dash_ability` system in `abilities.rs`.
pub fn dash_divine_steed() {
    // Standard dodge — handled by dash_ability system
}
